-----      


/*
Problem Statement: 
You are a database administrator. You want to use the data to answer a few questions about your customers, especially about the sales and profit coming from different states, money spent in marketing and various other factors such as COGS (Cost of Goods Sold), budget profit etc. You plan on using these insights to help find out which items are being sold the most. You have been provided with the sample of the overall customer data due to privacy issues. But you hope that these samples are enough for you to write fully functioning SQL queries to help answer the questions.
Dataset:

The 3 key datasets for this case study:

a. FactTable: The Fact Table has 14 columns mentioned below and 4200 rows. Date, ProductID, Profit, Sales, Margin, COGS, Total Expenses, Marketing, Inventory, Budget Profit, Budget COGS, Budget Margin, Budget Sales, and Area Code Note: COGS stands for Cost of Goods Sold

b. ProductTable: The ProductTable has four columns named Product Type, Product, ProductID, and Type. It has 13 rows which can be broken down into further details to retrieve the information mentioned in theFactTable.

c. LocationTable: Finaly, the LocationTable has 156 rows and follows a similar approach to ProductTable. It has four columns named Area Code, State, Market, and Market Size.

*/

--Create the Database CaseStudyOne ;

CREATE DATABASE CaseStudyOne ;
USE CaseStudyOne ;

--Import the tables fact, location, Product
SELECT * FROM fact ;
SELECT * FROM Location ;
SELECT * FROM Product ;


--============ Tasks to be performed===============

--1. Display the number of states present in the Location table.
SELECT 
	COUNT(DISTINCT State) AS Number_of_States    
FROM 
	Location ;
--------------------------------------------------
--2. How many products are of regular type?
SELECT 
	TYPE AS Product_type,
	COUNT(*) AS Number
FROM
	Product
GROUP BY 
	Type
	HAVING TYPE = 'Regular' ;
--------------------------------------------------
--3. How much spending has been done on marketing of product ID 1 ?

SELECT 
	ProductId,
	SUM(Marketing) AS Amount_Spent
FROM 
	fact
WHERE 
	ProductId = 1 
GROUP BY
	ProductId ;

-------------------------------------------------
--4. What is the minimum sales of a product?

SELECT 
	MIN(Sales) AS Minimum_Sale
FROM 
	fact;
------------------------------------------------
--5. Display the max Cost of Good Sold (COGS).

SELECT 
	MAX(COGS) AS Maximum_Cost_COGS
FROM 
	fact ;
------------------------------------------------
--6. Display the details of the product where product type is coffee.
SELECT 
	ProductId,
	Product_type,
	Product,
	Type
FROM 
	Product
WHERE
  Product_type = 'coffee' ;
-------------------------------------------------
--7. Display the details where total expenses are greater than 40.
SELECT * FROM fact ;

SELECT 
	ProductId,
	Total_Expenses
FROM 
	fact
WHERE
	Total_Expenses > 40 
ORDER BY
	ProductId, Total_Expenses ;
--------------------------------------------------
--8. What is the average sales in area code 719?
SELECT 
	Area_Code,
	AVG(Sales) AS AvgSales
FROM fact
GROUP BY 
	Area_Code
HAVING Area_Code  = 719 ;
--------------------------------------------------------
--9. Find out the total profit generated by Colorado state.



SELECT 
	
	SUM(f.Profit) AS Total_Profit_Colorado
FROM 
	fact f
INNER JOIN 
	Location l
	ON 
	f.Area_Code = l.Area_Code
WHERE l.State = 'Colorado' ;
--------------------------------------------------------


--10. Display the average inventory for each product ID.

SELECT 
	ProductId,
	AVG(Inventory) AS Average_Inventory
FROM
	fact 
GROUP BY 
	ProductId 
ORDER BY ProductId;
-------------------------------------------------------------------
--11. Display state in a sequential order in a LocationTable.
SELECT 
	DISTINCT(State)
FROM 
	Location
ORDER BY
	State ;

---------------------------------------------------------------------
--12. Display the average budget of the Product where the average budget margin should be greater than 100.


SELECT
	ProductId,
	AVG(Budget_Margin) AS avg_Budget
FROM 
	fact
GROUP BY 
	ProductId
HAVING 
	AVG(Budget_Margin) > 100 ;
-----------------------------------------------------------------
--13. What is the total sales done on date 2010-01-01?


SELECT 
    
	SUM(Sales) AS Total_Sales
FROM 
	FACT
WHERE 
    date='2010-01-01' ;

---------------------------------------------------------------
--14. Display the average total expense of each product ID on an individual date.
SELECT 
	ProductId,
	Date,
	AVG(Total_Expenses) AS Average_Total_Expenses 
FROM fact
GROUP BY 
	ProductId,
	Date
ORDER BY 
	ProductId,
	Date;

---------------------------------------------------------------------

--15. Display the table with the following attributes such as date, productID,product_type, product, sales, profit, state, area_code.


SELECT
    f.Date,
	f.ProductId,
	p.Product_Type,
	p.Product,
	f.Sales,
	f.Profit,
	l.State,
	l.Area_code

FROM fact f
JOIN Product p 
ON f.ProductId = p.ProductId
JOIN Location l ON f.Area_Code = l.Area_Code;

----------------------------------------------------------------------------------------------------
--16. Display the rank without any gap to show the saleswise rank.

--No gap means DENSE_RANK
SELECT * FROM fact;
SELECT * FROM Location ;
SELECT * FROM Product ;

SELECT 
	Sales,
	DENSE_RANK() OVER(ORDER BY Sales) AS SaleswiseRank
FROM 
	fact ;

--------------------------------------------------------

--17. Find the state wise profit and sales.
SELECT * FROM fact;
SELECT * FROM Location ;
SELECT * FROM Product ;


SELECT 
	l.State,
	SUM(Profit) AS state_profit,
	SUM(Sales) AS state_sales
FROM Location l
JOIN fact f
ON l.Area_Code = f.Area_Code
GROUP BY
	l.State 
ORDER BY
	state_profit ;

---------------------------------------------------------
--18. Find the state wise profit and sales along with the productname.
SELECT 
	l.State,
	p.Product AS product_name ,
	SUM(Profit) AS state_profit,
	SUM(Sales) AS state_sales	
FROM Location l
JOIN fact f
ON l.Area_Code = f.Area_Code
JOIN Product p
ON f.ProductId=p.ProductId
GROUP BY
	l.State,
	p.Product
ORDER BY
	l.State,
	state_profit DESC;


--19. If there is an increase in sales of 5%, calculate the increased sales.
SELECT
	Date,
	ProductId,
	Sales AS Original_Sales,
	Sales*1.05  AS Increased_Sales,
	(Sales*0.05) AS Sales_Increase_Amount
FROM 
	fact ;



--20. Find the maximum profit along with the product ID and producttype.
--Method 1: Using subquery
SELECT 
	f.ProductId, 
	p.Product_type, 
	f.Profit
FROM 
	fact f
JOIN Product p ON f.ProductId = p.ProductId 
WHERE 
	f.Profit = (
		SELECT MAX(Profit) 
		FROM fact
		) ;
--Method 2: Using TOP with ORDER BY
SELECT TOP 1
	f.ProductId, 
	p.Product_Type,
	f.Profit
FROM 
	fact f
JOIN Product p ON f.ProductId = p.ProductId
ORDER BY f.Profit DESC ;

--21. Create a stored procedure to fetch the result according to the product type from ProductTable.

--Create a stored procedure
CREATE PROCEDURE sp_GetProductsByType (@ProductType VARCHAR(50))
AS
BEGIN
	SELECT *
	FROM Product 
	WHERE Product_Type = @ProductType ;
END ;
GO

--Execute the stored procedure
EXEC sp_GetProductsByType 'Coffee' ;



--22. Write a query by creating a condition in which if the total expenses is less than 60 then it is a profit or else loss.
SELECT
	Date,
	ProductId,
	Total_Expenses,
	CASE
		WHEN Total_Expenses < 60 THEN 'Profit'
		ELSE 'Loss'
	END AS Profit_Loss_Status
FROM fact ;

--24. Give the total weekly sales value with the date and productID details. Use roll-up to pull the data in hierarchical order.
SELECT
	DATEPART(year, Date) AS Year
	,DATEPART(week, Date) AS Week
	,ProductId,
	SUM(Sales) AS Total_Sales
FROM 
	fact 
GROUP BY ROLLUP(DATEPART(year, Date), DATEPART(week, Date), ProductId)
Order BY Year, Week, ProductId ;

--25. Apply union and intersection operator on the tables which consist of attribute area code.
--UNION
SELECT Area_Code FROM fact 
UNION
SELECT Area_Code FROM Location ;


SELECT Area_Code FROM fact 
UNION ALL
SELECT Area_Code FROM Location ;

SELECT Area_Code FROM fact 
INTERSECT
SELECT Area_Code FROM Location ;
--26. Create a user-defined function for the product table to fetch aparticular product type based upon the user’s preference.


--27. Change the product type from coffee to tea where product ID is 1and undo it.

--28. Display the date, product ID and sales where total expensesare between 100 to 200.


--29. Delete the records in the Product Table for regulartype.


--30. Display the ASCII value of the fifth character from the columnProduct